### PR TITLE
support numpy 2 with spiceypy workaround

### LINKED ISSUE #20: Support numpy v2
Curryer requires numpy<2.0.0 which is causing dependency resolution problems for other packages that use Curryer but also want to use a recent version of numpy. 

Curryer should be updated to use numpy <3 but should continue supporting 1.x versions as some packages haven't added support for v2 yet.

### LINKED ISSUE #147: Update Curryer to work with SpiceyPy 8.1.0 (released 4/4/2026)
# Context

Curryer appears to be incompatible with changes introduced to SpiceyPy in verson 8.1.0.

# Stack Trace 

Even importing curryer fails.

```
>>> import curryer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    import curryer
  File "/workspaces/curryer/curryer/__init__.py", line 7, in <module>
    from . import compute, kernels, meta, spicetime, spicierpy, tle, utils
  File "/workspaces/curryer/curryer/compute/__init__.py", line 6, in <module>
    from . import constants, elevation, ephemeris, pointing, spatial
  File "/workspaces/curryer/curryer/compute/ephemeris.py", line 23, in <module>
    from .. import spicierpy
  File "/workspaces/curryer/curryer/spicierpy/__init__.py", line 10, in <module>
    from spiceypy import *
  File "/workspaces/curryer/.venv/lib/python3.13/site-packages/spiceypy/__init__.py", line 36, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
AttributeError: module 'spiceypy' has no attribute 'exceptionsstypes'
```

### PR DESCRIPTION
**Pull request by mmaclay**
This pull request updates the codebase to support both NumPy 1.x and 2.x, removes a restrictive pin on the `spiceypy` version, and improves compatibility and error handling for recent upstream changes. It also updates tests and code to use consistent `np.nan` usage and adapts to error message changes in NumPy 2.

**NumPy 2 compatibility:**
- Updated `curryer/spicetime/convert.py` to handle API changes in NumPy 2, including replacing the removed `__array_prepare__` with enhanced logic in `__array_wrap__`, and adding version checks to ensure correct behavior across NumPy versions. [[1]](diffhunk://#diff-71c186efbbfd9559f1bd4d12f5baef73aa92c453f95c15cbbc760c81d1acc31fR41-R42) [[2]](diffhunk://#diff-71c186efbbfd9559f1bd4d12f5baef73aa92c453f95c15cbbc760c81d1acc31fL510-L526) [[3]](diffhunk://#diff-71c186efbbfd9559f1bd4d12f5baef73aa92c453f95c15cbbc760c81d1acc31fL537-R548)
- Relaxed the `numpy` dependency version pin in `pyproject.toml` to allow NumPy 2.x, and added a flake8 rule for NumPy 2 migration warnings. [[1]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L56-R60) [[2]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R113)
- Updated tests to match new NumPy 2 error messages, using regex to allow for both old and new wording. [[1]](diffhunk://#diff-d9b2c5e6fa28d11aae38e26064999f0efa4493f20881a4e9965f1eb01ad5b434L148-R150) [[2]](diffhunk://#diff-d9b2c5e6fa28d11aae38e26064999f0efa4493f20881a4e9965f1eb01ad5b434L310-R312)

**SpiceyPy compatibility:**
- Removed the upper version pin on `spiceypy` and implemented a fallback import mechanism in `curryer/spicierpy/__init__.py` to work around a broken `__all__` in SpiceyPy 8.1.0–8.1.2. [[1]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L56-R60) [[2]](diffhunk://#diff-5969511830bf25fefcde9e098a56560b0f2937296134d03a5571cb4f2d3202ddR10-R19)

**Code and test cleanup:**
- Replaced all uses of `np.NaN` with the canonical `np.nan` for consistency and to avoid deprecation warnings. [[1]](diffhunk://#diff-2dc9844d34ae893d0e0b16dcaee7dbb8c0aa014106ae52bb78a5f6d0a6a5519cL459-R459) [[2]](diffhunk://#diff-be539da8ff8b51b50a304be0f9e124ff43c7c7382f64cfcdffc4251163aaa0faL422-R426)

These changes ensure that the codebase remains compatible with the latest upstream dependencies and continues to function correctly with both older and newer versions of NumPy and SpiceyPy.

### CODE REVIEW

**Comment by mmaclay** [comment]
I put in two bug reports at SpiceyPy. Once addressed, we can clean upour dependencies significantly. But this code should work for now.

https://github.com/AndrewAnnex/SpiceyPy/issues/558
https://github.com/AndrewAnnex/SpiceyPy/issues/559

**Review by mwatwood-cu — APPROVED** [review]
2 non code aspects to address with the approval of this.

1. Notify / test this dependency change with downstream users like the Libera and Clarreo teams
2. I think it is worth making an issue in the repo to capture the need to update this after / if the spiceypy bug is resolved.
