### PR TITLE
pin spiceypy below 8.1

### LINKED ISSUE #147: Update Curryer to work with SpiceyPy 8.1.0 (released 4/4/2026)
# Context

Curryer appears to be incompatible with changes introduced to SpiceyPy in verson 8.1.0.

# Stack Trace 

Even importing curryer fails.

```
>>> import curryer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    import curryer
  File "/workspaces/curryer/curryer/__init__.py", line 7, in <module>
    from . import compute, kernels, meta, spicetime, spicierpy, tle, utils
  File "/workspaces/curryer/curryer/compute/__init__.py", line 6, in <module>
    from . import constants, elevation, ephemeris, pointing, spatial
  File "/workspaces/curryer/curryer/compute/ephemeris.py", line 23, in <module>
    from .. import spicierpy
  File "/workspaces/curryer/curryer/spicierpy/__init__.py", line 10, in <module>
    from spiceypy import *
  File "/workspaces/curryer/.venv/lib/python3.13/site-packages/spiceypy/__init__.py", line 36, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
AttributeError: module 'spiceypy' has no attribute 'exceptionsstypes'
```

### PR DESCRIPTION
**Pull request by mmaclay**
SpiceyPy 8.1 broke curryer. Patching this hot fix specifically to enable Libera SDC development.

### CODE REVIEW

**Review by BStoneLASP — APPROVED** [review]
Looks great. Please either keep the ticket open after this or create a new one for a longer term fix (might just need to wait until they release a patch).
