### ISSUE TITLE
Update Curryer to work with SpiceyPy 8.1.0 (released 4/4/2026)

### ISSUE THREAD

**Issue by medley56** [lasp/curryer#147]
# Context

Curryer appears to be incompatible with changes introduced to SpiceyPy in verson 8.1.0.

# Stack Trace 

Even importing curryer fails.

```
>>> import curryer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    import curryer
  File "/workspaces/curryer/curryer/__init__.py", line 7, in <module>
    from . import compute, kernels, meta, spicetime, spicierpy, tle, utils
  File "/workspaces/curryer/curryer/compute/__init__.py", line 6, in <module>
    from . import constants, elevation, ephemeris, pointing, spatial
  File "/workspaces/curryer/curryer/compute/ephemeris.py", line 23, in <module>
    from .. import spicierpy
  File "/workspaces/curryer/curryer/spicierpy/__init__.py", line 10, in <module>
    from spiceypy import *
  File "/workspaces/curryer/.venv/lib/python3.13/site-packages/spiceypy/__init__.py", line 36, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
AttributeError: module 'spiceypy' has no attribute 'exceptionsstypes'
```

**Comment by maxineofficial** [comment]
Related to #20
